export const defaultCategoryRules: Record<string, string[]> = {
  "Food and Dining": [
    "swiggy",
    "zomato",
    "restaurant",
    "cafe",
    "eatery",
    "hungerbox",
    "pizza",
    "burger",
    "tea",
    "coffee",
    "chai",
    "snacks",
    "bakery",
    "juice",
    "canteen",
    "tiffin"
  ],
  Transportation: ["uber", "ola", "rapido", "metro", "irctc", "rail", "bus", "taxi"],
  Travel: ["makemytrip", "goibibo", "flight", "hotel", "yatra", "airline"],
  Shopping: [
    "amazon",
    "flipkart",
    "myntra",
    "ajio",
    "nykaa",
    "zudio",
    "mall",
    "stationery",
    "stationary",
    "books",
    "book store",
    "bookshop",
    "xerox",
    "photocopy",
    "print",
    "office supplies"
  ],
  Groceries: [
    "blinkit",
    "zepto",
    "instamart",
    "bigbasket",
    "bbnow",
    "grocery",
    "supermarket",
    "hypermarket",
    "mart",
    "dmart",
    "reliance retail",
    "reliance smart",
    "smart bazaar",
    "reliance fresh",
    "jiomart",
    "nature's basket",
    "star bazaar",
    "spencers",
    "spar",
    "more",
    "fresh"
  ],
  Entertainment: ["netflix", "spotify", "bookmyshow", "hotstar", "prime video", "pvr"],
  Utilities: ["electricity", "water", "gas", "broadband", "recharge", "mobile bill", "dth"],
  Fuel: ["petrol", "diesel", "fuel", "iocl", "hpcl", "bpcl", "indianoil", "shell"],
  Healthcare: ["medical", "pharmacy", "hospital", "apollo", "1mg", "netmeds", "medico"],
  "Finance and Wallet": ["paytm", "phonepe", "gpay", "wallet", "cred", "upi collect"],
  Investments: ["mutual fund", "sip", "zerodha", "groww", "upstox", "coin"],
  Insurance: ["insurance", "policy", "premium", "lombard", "ergo", "star health"],
  Education: ["school", "college", "course", "udemy", "coursera", "byjus", "unacademy"],
  "Government and Tax": ["challan", "gst", "tax", "fastag", "toll", "income tax"]
};
