export const merchantCategoryMap: Record<string, string> = {
  // Food and Dining
  SWIGGY: "Food and Dining",
  ZOMATO: "Food and Dining",
  EATCLUB: "Food and Dining",
  ETERNAL: "Food and Dining",
  DOMINOS: "Food and Dining",
  PIZZAHUT: "Food and Dining",
  STARBUCKS: "Food and Dining",
  CAFECOFFEEDAY: "Food and Dining",
  BARBEQUENATION: "Food and Dining",
  MCDONALDS: "Food and Dining",
  KFC: "Food and Dining",
  BURGERKING: "Food and Dining",
  HUNGERBOX: "Food and Dining",
  TEA: "Food and Dining",
  COFFEE: "Food and Dining",
  CHAI: "Food and Dining",
  BAKERY: "Food and Dining",
  JUICE: "Food and Dining",
  CANTEEN: "Food and Dining",

  // Transportation and Travel
  IRCTC: "Transportation",
  UBER: "Transportation",
  OLA: "Transportation",
  RAPIDO: "Transportation",
  REDBUS: "Transportation",
  MAKEMYTRIP: "Travel",
  GOIBIBO: "Travel",
  EASEMYTRIP: "Travel",
  YATRA: "Travel",
  AIRINDIA: "Travel",
  INDIGO: "Travel",
  AKASA: "Travel",
  VISTARA: "Travel",

  // Shopping
  AMAZON: "Shopping",
  FLIPKART: "Shopping",
  MYNTRA: "Shopping",
  AJIO: "Shopping",
  NYKAA: "Shopping",
  MEESHO: "Shopping",
  TATACLIQ: "Shopping",
  ZUDIO: "Shopping",
  TRENDS: "Shopping",
  WESTSIDE: "Shopping",
  LIFESTYLE: "Shopping",
  RELIANCEDIGITAL: "Shopping",
  CROMA: "Shopping",
  VIJAYSALES: "Shopping",
  IKEA: "Shopping",
  FIRSTCRY: "Shopping",
  HOPSCOTCH: "Shopping",
  STATIONERY: "Shopping",
  STATIONARY: "Shopping",
  XEROX: "Shopping",
  PHOTOCOPY: "Shopping",
  PRINTSHOP: "Shopping",
  BOOKSTORE: "Shopping",
  BOOKSHOP: "Shopping",
  OFFICEDEPOT: "Shopping",

  // Groceries
  BLINKIT: "Groceries",
  ZEPTO: "Groceries",
  INSTAMART: "Groceries",
  BIGBASKET: "Groceries",
  BBNOW: "Groceries",
  DMART: "Groceries",
  AVENUESUPERMART: "Groceries",
  DMARTREADY: "Groceries",
  JIOMART: "Groceries",
  "RELIANCE RETAIL": "Groceries",
  "RELIANCE SMART": "Groceries",
  SMARTBAZAAR: "Groceries",
  "SMART BAZAAR": "Groceries",
  "RELIANCE FRESH": "Groceries",
  FRESHPIK: "Groceries",
  BIGBAZAAR: "Groceries",
  "BIG BAZAAR": "Groceries",
  MOREMEGASTORE: "Groceries",
  MORE: "Groceries",
  STARQUICK: "Groceries",
  SPENCERS: "Groceries",
  SPAR: "Groceries",
  EASYDAY: "Groceries",
  HERITAGEFRESH: "Groceries",
  RATNADEEP: "Groceries",
  VIJETHA: "Groceries",
  NILGIRIS: "Groceries",
  NELLAI: "Groceries",
  DAILYNINJA: "Groceries",
  COUNTRYDELIGHT: "Groceries",
  "MILK BASKET": "Groceries",
  STARBAZAAR: "Groceries",
  NATURESBASKET: "Groceries",

  // Entertainment
  NETFLIX: "Entertainment",
  SPOTIFY: "Entertainment",
  BOOKMYSHOW: "Entertainment",
  HOTSTAR: "Entertainment",
  SONYLIV: "Entertainment",
  ZEE5: "Entertainment",
  PRIMEVIDEO: "Entertainment",
  YOUTUBEPREMIUM: "Entertainment",
  INOX: "Entertainment",
  PVR: "Entertainment",

  // Utilities and Bills
  BESCOM: "Utilities",
  MSEB: "Utilities",
  TANGEDCO: "Utilities",
  ADANI: "Utilities",
  TATAPOWER: "Utilities",
  AIRTEL: "Utilities",
  JIO: "Utilities",
  VI: "Utilities",
  VODAFONE: "Utilities",
  BSNL: "Utilities",
  ACTFIBERNET: "Utilities",
  HATHWAY: "Utilities",
  TATASKY: "Utilities",
  AIRTELDTH: "Utilities",

  // Fuel
  INDIANOIL: "Fuel",
  IOCL: "Fuel",
  BPCL: "Fuel",
  HPCL: "Fuel",
  NAYARA: "Fuel",
  SHELL: "Fuel",

  // Healthcare
  APOLLO: "Healthcare",
  PHARMEASY: "Healthcare",
  NETMEDS: "Healthcare",
  TATA1MG: "Healthcare",
  MEDPLUS: "Healthcare",
  PRACTO: "Healthcare",
  SRL: "Healthcare",
  THYROCARE: "Healthcare",
  REDCLIFFE: "Healthcare",

  // Finance / Wallet / Investment
  PAYTM: "Finance and Wallet",
  PHONEPE: "Finance and Wallet",
  GPAY: "Finance and Wallet",
  GOOGLEPAY: "Finance and Wallet",
  MOBIKWIK: "Finance and Wallet",
  FREECHARGE: "Finance and Wallet",
  CRED: "Finance and Wallet",
  PAYPAL: "Finance and Wallet",
  RAZORPAY: "Finance and Wallet",
  CASHFREE: "Finance and Wallet",
  UPSTOX: "Investments",
  ZERODHA: "Investments",
  GROWW: "Investments",
  KUVERA: "Investments",
  COIN: "Investments",

  // Education
  BYJUS: "Education",
  UNACADEMY: "Education",
  COURSERA: "Education",
  UDEMY: "Education",
  SCALER: "Education",
  UPGRAD: "Education",

  // Insurance
  POLICYBAZAAR: "Insurance",
  ACKO: "Insurance",
  HDFCERGO: "Insurance",
  STARHEALTH: "Insurance",
  NIVA: "Insurance",
  ICICILOMBARD: "Insurance",

  // Government and Tax
  FASTAG: "Government and Tax",
  CHALLAN: "Government and Tax",
  GST: "Government and Tax",
  INCOMETAX: "Government and Tax",
  NSDL: "Government and Tax",
  TIN: "Government and Tax"
};

export const sortedMerchantPatterns = Object.keys(merchantCategoryMap).sort(
  (a, b) => b.length - a.length
);
